name: EAS Build

on:
  workflow_call:
    inputs:
      PLATFORM:
        required: true
        type: string
      PROFILE:
        required: false
        type: string
        default: production

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git pull origin ${{ github.ref_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 6.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS
        run: eas build --profile ${{ inputs.PROFILE }} --platform ${{ inputs.PLATFORM }} --non-interactive
